// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\VINICIUS-VN\Desktop\projetos\PortifolioProjetos\secbank.api\interfaces\repository/IAccountHolderRepository.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "secbank.api/models"
)

// MockIAccountHolderRepository is a mock of IAccountHolderRepository interface.
type MockIAccountHolderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountHolderRepositoryMockRecorder
}

// MockIAccountHolderRepositoryMockRecorder is the mock recorder for MockIAccountHolderRepository.
type MockIAccountHolderRepositoryMockRecorder struct {
	mock *MockIAccountHolderRepository
}

// NewMockIAccountHolderRepository creates a new mock instance.
func NewMockIAccountHolderRepository(ctrl *gomock.Controller) *MockIAccountHolderRepository {
	mock := &MockIAccountHolderRepository{ctrl: ctrl}
	mock.recorder = &MockIAccountHolderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountHolderRepository) EXPECT() *MockIAccountHolderRepositoryMockRecorder {
	return m.recorder
}

// R_Create mocks base method.
func (m *MockIAccountHolderRepository) R_Create(customer models.AccountHolder) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R_Create", customer)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// R_Create indicates an expected call of R_Create.
func (mr *MockIAccountHolderRepositoryMockRecorder) R_Create(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R_Create", reflect.TypeOf((*MockIAccountHolderRepository)(nil).R_Create), customer)
}

// R_Delete mocks base method.
func (m *MockIAccountHolderRepository) R_Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R_Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// R_Delete indicates an expected call of R_Delete.
func (mr *MockIAccountHolderRepositoryMockRecorder) R_Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R_Delete", reflect.TypeOf((*MockIAccountHolderRepository)(nil).R_Delete), id)
}

// R_Get mocks base method.
func (m *MockIAccountHolderRepository) R_Get(id int) (*models.AccountHolder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R_Get", id)
	ret0, _ := ret[0].(*models.AccountHolder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// R_Get indicates an expected call of R_Get.
func (mr *MockIAccountHolderRepositoryMockRecorder) R_Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R_Get", reflect.TypeOf((*MockIAccountHolderRepository)(nil).R_Get), id)
}

// R_List mocks base method.
func (m *MockIAccountHolderRepository) R_List() (*[]models.AccountHolder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R_List")
	ret0, _ := ret[0].(*[]models.AccountHolder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// R_List indicates an expected call of R_List.
func (mr *MockIAccountHolderRepositoryMockRecorder) R_List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R_List", reflect.TypeOf((*MockIAccountHolderRepository)(nil).R_List))
}

// R_Update mocks base method.
func (m *MockIAccountHolderRepository) R_Update(customer models.AccountHolder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R_Update", customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// R_Update indicates an expected call of R_Update.
func (mr *MockIAccountHolderRepositoryMockRecorder) R_Update(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R_Update", reflect.TypeOf((*MockIAccountHolderRepository)(nil).R_Update), customer)
}
