name: Build, Push Docker Image, and Deploy to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t secbank -f secbank.api/Dockerfile ./secbank.api

      - name: Tag Docker Image
        run: |
          docker tag secbank:latest 400768006621.dkr.ecr.us-east-1.amazonaws.com/secbank:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 400768006621.dkr.ecr.us-east-1.amazonaws.com/secbank:latest

      - name: Force New Deployment on ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service \
            --cluster SecBankCluster \
            --service SecBankApi \
            --force-new-deployment